### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by CengizhanmD** [mathworks/build-glibc-bz-19329-patch#11]
Hello, 

I know the same thing has been asked before, but I tried all the solutions given and still have the same issue. Basically after I install, I get an error, and when I run `sudo apt --fix-broken install`, this error is generated

```sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... failed.
The following packages have unmet dependencies:
 glibc-doc : Depends: glibc-doc-reference (>= 2.18) but it is not installed
 libc6 : Breaks: libc6:i386 (!= 2.31-0ubuntu9.12.ubuntu.focal.custom) but 2.31-0ubuntu9.12 is installed
 libc6:i386 : Breaks: libc6 (!= 2.31-0ubuntu9.12) but 2.31-0ubuntu9.12.ubuntu.focal.custom is installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
E: Unable to correct dependencies
```

I manually downloaded libc6 and libc6:i386 as well and tried to install with `dpkg -i *.deb`, but it just generated the same error.

**Comment by josmartin** [comment]
When you see something like this (i.e. you are installing libc and NOT installing libc-doc) and get a dependency between them then you also need to install the specifically built libc-doc package (or other such package).
