### ISSUE TITLE
SLES15 support

### ISSUE THREAD

**Issue by jdswebb** [mathworks/build-glibc-bz-19329-patch#12]
Hi,

Is it possible to apply the patch on SLES15? I have been trying to figure it out without any success as we unfortunately see the tls bug almost every time we run MATLAB/Simulink (2022a-2023b).

Thanks

**Comment by josmartin** [comment]
@jdswebb You will need to work out what the equivalent build system for SLES is to `rpmbuild` on RHEL and `dpkg-buildpackage` on Debian and Ubuntu. Basically, the docker container that this repo makes actually runs the compilation build of the underlying packages from source code to produce something that you can then install. I'm afraid I'm very unfamiliar with SLES and how it operates so can't give more advice than "adapt the Dockerfile such that you start from the appropriate SLES version, install the package manager build system (which usually includes a way to get the source files to build from, apply the appropriate patches (we should have one for the glibc that you are building - probably!) and then build" - I realize that isn't trivial but its basically what I did to transition from Ubuntu (that I know most about) to RHEL (for which we do have an example build). I'll keep this issue open for a while in case you want to have something of a conversation about how to possibly go about the above suggestion.

**Comment by jdswebb** [comment]
Thanks for the reply! What you described is how I understood the process myself but unfortunately I am also unfamiliar with SLES and couldn't find too much information online about how to do this sort of thing with it. We may be able to use RHEL8.8 instead which as I understand it from the docs should already have the custom patched glibc2.28. If that doesn't work out I'll revisit this (and post here if I have any success) but it seems like it could take quite a while to figure it all out.

**Comment by josmartin** [comment]
@jdswebb Glad that you'd already groked the overall process, and once again sorry I don't know more about SLES. General google searches didn't really help me get to grips with how SLES builds itself. If you can move to RHEL 8.8 that would certainly solve your issues - as you point out they chose to incorporate these patches in their glibc (at which point I stopped building RHEL patches here).
