### ISSUE TITLE
backport into rhel and (debian|ubuntu)?

### ISSUE THREAD

**Issue by wumpus** [mathworks/build-glibc-bz-19329-patch#3]
I don't know what polices are for rhel and debian|ubuntu are for libc in particular, but distros do backport fixes on a regular basis -- has anyone been in touch about this one?

**Comment by josmartin** [comment]
@wumpus We have noted that both RHEL and debian are aware of this issue. 

Interestingly RHEL have *just* integrated the bz-19329 patch into [glibc-2.28-189.1.el8](https://git.almalinux.org/rpms/glibc/commit/385bc0f199bf51199143fe12b857f4983db76e48). It appear that the change actually went into [build 2.28-175 ](https://git.almalinux.org/rpms/glibc/src/commit/385bc0f199bf51199143fe12b857f4983db76e48/SPECS/glibc.spec#L2721) and got released with 2.28-189. I'll be updating the main page of this repo to indicate that for RHEL 8 (and related versions) users no longer need to patch (and only need this repo if they are using an earlier version of libc 2.28). 

We are still awaiting build patches from debian and related distro's but have no timeline on if they are considering this as an important patch to apply.

**Comment by wumpus** [comment]
Thank you @josmartin -- I was hoping this was the answer!

If you need me to show up to lobby debian/ubuntu/whoever in favor of this patch, just let me know... this is exactly the kind of fix that everyone's "long term support" needs to backport.
