### ISSUE TITLE
Problem Installing patch on Ubuntu 20.04

### ISSUE THREAD

**Issue by h-sh-h** [mathworks/build-glibc-bz-19329-patch#6]
Hello,
I downloaded the ALL packages tar file the tried to install it with the following command `sudo dpkg -i *` 
but I get the following errors :

(Reading database ... 337970 files and directories currently installed.)
Preparing to unpack glibc-doc_2.31-0ubuntu9.9.ubuntu.focal.custom_all.deb ...
Unpacking glibc-doc (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack glibc-source_2.31-0ubuntu9.9.ubuntu.focal.custom_all.deb ...
Unpacking glibc-source (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack libc6_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking libc6:amd64 (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack libc6-dbg_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking libc6-dbg:amd64 (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack libc6-dev_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking libc6-dev:amd64 (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack libc6-dev-i386_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking libc6-dev-i386 (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack libc6-dev-x32_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking libc6-dev-x32 (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
dpkg: regarding libc6-i386_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb containing libc6-i386:
 libc6-i386 conflicts with libc6-amd64
  libc6-amd64:i386 (version 2.31-0ubuntu9.9) is present and installed.

dpkg: error processing archive libc6-i386_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb (--install):
 conflicting packages - not installing libc6-i386
Preparing to unpack libc6-pic_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking libc6-pic:amd64 (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack libc6-prof_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking libc6-prof:amd64 (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
dpkg: regarding libc6-x32_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb containing libc6-x32:
 libc6-x32 conflicts with libc6-amd64
  libc6-amd64:i386 (version 2.31-0ubuntu9.9) is present and installed.

dpkg: error processing archive libc6-x32_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb (--install):
 conflicting packages - not installing libc6-x32
Preparing to unpack libc-bin_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking libc-bin (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack libc-dev-bin_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking libc-dev-bin (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack locales_2.31-0ubuntu9.9.ubuntu.focal.custom_all.deb ...
Unpacking locales (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack locales-all_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking locales-all (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack nscd_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking nscd (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
dpkg: dependency problems prevent configuration of glibc-doc:
 glibc-doc depends on glibc-doc-reference (>= 2.18); however:
  Package glibc-doc-reference is not installed.

dpkg: error processing package glibc-doc (--install):
 dependency problems - leaving unconfigured
Setting up glibc-source (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
dpkg: error processing package libc6:amd64 (--install):
 package libc6:amd64 2.31-0ubuntu9.9.ubuntu.focal.custom cannot be configured because libc6:i386 is at a different version (2.31-0ubuntu9.9)
dpkg: dependency problems prevent configuration of libc6-dbg:amd64:
 libc6-dbg:amd64 depends on libc6 (= 2.31-0ubuntu9.9.ubuntu.focal.custom); however:
  Package libc6:amd64 is not configured yet.

dpkg: error processing package libc6-dbg:amd64 (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libc6-dev:amd64:
 libc6-dev:amd64 depends on libc6 (= 2.31-0ubuntu9.9.ubuntu.focal.custom); however:
  Package libc6:amd64 is not configured yet.

dpkg: error processing package libc6-dev:amd64 (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libc6-dev-i386:
 libc6-dev-i386 depends on libc6-i386 (= 2.31-0ubuntu9.9.ubuntu.focal.custom); however:
  Package libc6-i386 is not installed.
 libc6-dev-i386 depends on libc6-dev (= 2.31-0ubuntu9.9.ubuntu.focal.custom); however:
  Package libc6-dev:amd64 is not configured yet.

dpkg: error processing package libc6-dev-i386 (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libc6-dev-x32:
 libc6-dev-x32 depends on libc6-x32 (= 2.31-0ubuntu9.9.ubuntu.focal.custom); however:
  Package libc6-x32 is not installed.
 libc6-dev-x32 depends on libc6-dev-i386 (= 2.31-0ubuntu9.9.ubuntu.focal.custom); however:
  Package libc6-dev-i386 is not configured yet.
 libc6-dev-x32 depends on libc6-dev (= 2.31-0ubuntu9.9.ubuntu.focal.custom); however:
  Package libc6-dev:amd64 is not configured yet.

dpkg: error processing package libc6-dev-x32 (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libc6-pic:amd64:
 libc6-pic:amd64 depends on libc6 (= 2.31-0ubuntu9.9.ubuntu.focal.custom); however:
  Package libc6:amd64 is not configured yet.

dpkg: error processing package libc6-pic:amd64 (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libc6-prof:amd64:
 libc6-prof:amd64 depends on libc6 (= 2.31-0ubuntu9.9.ubuntu.focal.custom); however:
  Package libc6:amd64 is not configured yet.

dpkg: error processing package libc6-prof:amd64 (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libc-bin:
 libc-bin depends on libc6 (>> 2.31); however:
  Package libc6:amd64 is not configured yet.
 libc-bin depends on libc6 (<< 2.32); however:
  Package libc6:amd64 is not configured yet.

dpkg: error processing package libc-bin (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libc-dev-bin:
 libc-dev-bin depends on libc6 (>> 2.31); however:
  Package libc6:amd64 is not configured yet.
 libc-dev-bin depends on libc6 (<< 2.32); however:
  Package libc6:amd64 is not configured yet.

dpkg: error processing package libc-dev-bin (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of locales:
 locales depends on libc-bin (>> 2.31); however:
  Package libc-bin is not configured yet.

dpkg: error processing package locales (--install):
 dependency problems - leaving unconfigured
Setting up locales-all (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
dpkg: dependency problems prevent configuration of nscd:
 nscd depends on libc6 (>> 2.31); however:
  Package libc6:amd64 is not configured yet.
 nscd depends on libc6 (<< 2.32); however:
  Package libc6:amd64 is not configured yet.

dpkg: error processing package nscd (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 libc6-i386_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb
 libc6-x32_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb
 glibc-doc
 libc6:amd64
 libc6-dbg:amd64
 libc6-dev:amd64
 libc6-dev-i386
 libc6-dev-x32
 libc6-pic:amd64
 libc6-prof:amd64
 libc-bin
 libc-dev-bin
 locales
 nscd

What should I do ?

**Comment by h-sh-h** [comment]
I removed "libc6-amd64:i386"

But I get the following errors :

(Reading database ... 338276 files and directories currently installed.)
Preparing to unpack glibc-doc_2.31-0ubuntu9.9.ubuntu.focal.custom_all.deb ...
Unpacking glibc-doc (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack glibc-source_2.31-0ubuntu9.9.ubuntu.focal.custom_all.deb ...
Unpacking glibc-source (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack libc6_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking libc6:amd64 (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack libc6-dbg_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking libc6-dbg:amd64 (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack libc6-dev_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking libc6-dev:amd64 (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack libc6-dev-i386_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking libc6-dev-i386 (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack libc6-dev-x32_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking libc6-dev-x32 (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack libc6-i386_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking libc6-i386 (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Replaced by files in installed package libc6:i386 (2.31-0ubuntu9.9) ...
Preparing to unpack libc6-pic_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking libc6-pic:amd64 (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack libc6-prof_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking libc6-prof:amd64 (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack libc6-x32_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking libc6-x32 (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack libc-bin_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking libc-bin (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack libc-dev-bin_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking libc-dev-bin (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack locales_2.31-0ubuntu9.9.ubuntu.focal.custom_all.deb ...
Unpacking locales (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack locales-all_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking locales-all (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Preparing to unpack nscd_2.31-0ubuntu9.9.ubuntu.focal.custom_amd64.deb ...
Unpacking nscd (2.31-0ubuntu9.9.ubuntu.focal.custom) over (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Setting up glibc-source (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
dpkg: error processing package libc6:amd64 (--install):
 package libc6:amd64 2.31-0ubuntu9.9.ubuntu.focal.custom cannot be configured because libc6:i386 is at a different version (2.31-0ubuntu9.9)
Setting up locales-all (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
dpkg: libc6-i386: dependency problems, but configuring anyway as you requested:
 libc6-i386 depends on libc6 (= 2.31-0ubuntu9.9.ubuntu.focal.custom); however:
  Package libc6:amd64 is not configured yet.

Setting up libc6-i386 (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
dpkg: libc6-pic:amd64: dependency problems, but configuring anyway as you requested:
 libc6-pic:amd64 depends on libc6 (= 2.31-0ubuntu9.9.ubuntu.focal.custom); however:
  Package libc6:amd64 is not configured yet.

Setting up libc6-pic:amd64 (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
dpkg: libc6-prof:amd64: dependency problems, but configuring anyway as you requested:
 libc6-prof:amd64 depends on libc6 (= 2.31-0ubuntu9.9.ubuntu.focal.custom); however:
  Package libc6:amd64 is not configured yet.

Setting up libc6-prof:amd64 (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
dpkg: libc6-x32: dependency problems, but configuring anyway as you requested:
 libc6-x32 depends on libc6 (= 2.31-0ubuntu9.9.ubuntu.focal.custom); however:
  Package libc6:amd64 is not configured yet.

Setting up libc6-x32 (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
dpkg: libc-bin: dependency problems, but configuring anyway as you requested:
 libc-bin depends on libc6 (>> 2.31); however:
  Package libc6:amd64 is not configured yet.
 libc-bin depends on libc6 (<< 2.32); however:
  Package libc6:amd64 is not configured yet.

Setting up libc-bin (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
dpkg: libc-dev-bin: dependency problems, but configuring anyway as you requested:
 libc-dev-bin depends on libc6 (>> 2.31); however:
  Package libc6:amd64 is not configured yet.
 libc-dev-bin depends on libc6 (<< 2.32); however:
  Package libc6:amd64 is not configured yet.

Setting up libc-dev-bin (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Setting up locales (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
locales-all installed, skipping locales generation
dpkg: nscd: dependency problems, but configuring anyway as you requested:
 nscd depends on libc6 (>> 2.31); however:
  Package libc6:amd64 is not configured yet.
 nscd depends on libc6 (<< 2.32); however:
  Package libc6:amd64 is not configured yet.

Setting up nscd (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
dpkg: glibc-doc: dependency problems, but configuring anyway as you requested:
 glibc-doc depends on glibc-doc-reference (>= 2.18); however:
  Package glibc-doc-reference is not installed.

Setting up glibc-doc (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
dpkg: libc6-dbg:amd64: dependency problems, but configuring anyway as you requested:
 libc6-dbg:amd64 depends on libc6 (= 2.31-0ubuntu9.9.ubuntu.focal.custom); however:
  Package libc6:amd64 is not configured yet.

Setting up libc6-dbg:amd64 (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
dpkg: libc6-dev:amd64: dependency problems, but configuring anyway as you requested:
 libc6-dev:amd64 depends on libc6 (= 2.31-0ubuntu9.9.ubuntu.focal.custom); however:
  Package libc6:amd64 is not configured yet.

Setting up libc6-dev:amd64 (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Setting up libc6-dev-i386 (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
Setting up libc6-dev-x32 (2.31-0ubuntu9.9.ubuntu.focal.custom) ...
dpkg: man-db: dependency problems, but processing triggers anyway as you requested:
 man-db depends on libc6 (>= 2.28); however:
  Package libc6:amd64 is not configured yet.

Processing triggers for man-db (2.9.1-1) ...
dpkg: systemd: dependency problems, but processing triggers anyway as you requested:
 systemd depends on libc6 (>= 2.30); however:
  Package libc6:amd64 is not configured yet.

Processing triggers for systemd (245.4-4ubuntu3.17) ...
Errors were encountered while processing:
 libc6:amd64

**Comment by josmartin** [comment]
@h-sh-h Before installing the patches can you try to updating your system to the very latest of everything with 

```
apt-get update
apt-get upgrade
``` 

This will make sure that everything in your ubuntu system is up-to-date. 

In addition on a completely new ubuntu docker container I found I needed to do the following to get the install to complete successfully (since you may not have some of the required dependencies)

```
dpkg -i *.deb
apt-get --fix-broken install
dpkg -i *.deb
```

What I have just tested is from a latest pull of `ubuntu:20.04` I `apt-get` on `wget` so I can then download the allpackages tar. I un-tar'd it and did the above successfully. Hopefully this will help get your install completed.

**Comment by h-sh-h** [comment]
Thanks for the feedback.

Actually I spent a whole day working on dependencies and it gave me a headache. With no progress.

I just upgraded to the newest ubuntu 22. 

Now I am stuck with hardware opengl 😑. Although Matlab did recognize my GPU.

**Comment by m-usama-z** [comment]
> @h-sh-h Before installing the patches can you try to updating your system to the very latest of everything with
> 
> ```
> apt-get update
> apt-get upgrade
> ```
> 
> This will make sure that everything in your ubuntu system is up-to-date.
> 
> In addition on a completely new ubuntu docker container I found I needed to do the following to get the install to complete successfully (since you may not have some of the required dependencies)
> 
> ```
> dpkg -i *.deb
> apt-get --fix-broken install
> dpkg -i *.deb
> ```
> 
> What I have just tested is from a latest pull of `ubuntu:20.04` I `apt-get` on `wget` so I can then download the allpackages tar. I un-tar'd it and did the above successfully. Hopefully this will help get your install completed.

Hi, @josmartin . Kindly include the information provided in this comment in the Installation instructions in the README. Most non-linux-savvy people like me need it and preferably, they shouldn't have to search the repo's issues in order to get it :) Thank you!

**Comment by m-usama-z** [comment]
Hi, @josmartin . Kindly also include in the README that the `dpkg -i *.deb` command is meant to install all the packages provided in the `all_packages.tar.gz` file. I only figured this out after reading the issues.
